# Generated by Django 4.2 on 2024-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_in_ctn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_per_ctn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
